import { User, Job, Message, Review, Complaint } from '../types';

export const SKILLS = [
  'React', 'Vue', 'Angular', 'TypeScript', 'JavaScript', 'Node.js',
  'Python', 'Django', 'FastAPI', 'Go', 'Rust', 'Java', 'Spring',
  'PHP', 'Laravel', 'Ruby', 'Rails', 'Swift', 'Kotlin',
  'Flutter', 'React Native', 'PostgreSQL', 'MySQL', 'MongoDB',
  'Redis', 'Docker', 'Kubernetes', 'AWS', 'GCP', 'Azure',
  'GraphQL', 'REST API', 'UI/UX', 'Figma', 'CSS', 'Tailwind CSS',
];

export const INITIAL_USERS: User[] = [
  {
    id: 'admin1',
    name: 'Администратор',
    email: 'admin@maxdev.ru',
    password: 'admin123',
    role: 'administrator',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=admin-maxdev&backgroundColor=000000',
    createdAt: '2024-01-01T00:00:00Z',
    isBlocked: false,
  },
  {
    id: 'client1',
    name: 'Алексей Петров',
    email: 'client@maxdev.ru',
    password: 'client123',
    role: 'client',
    bio: 'Владелец стартапа, ищу опытных разработчиков',
    createdAt: '2024-01-05T00:00:00Z',
    isBlocked: false,
  },
  {
    id: 'client2',
    name: 'Марина Иванова',
    email: 'marina@example.ru',
    password: 'pass123',
    role: 'client',
    bio: 'Маркетинговое агентство',
    createdAt: '2024-02-10T00:00:00Z',
    isBlocked: false,
  },
  {
    id: 'freelancer1',
    name: 'Дмитрий Соколов',
    email: 'freelancer@maxdev.ru',
    password: 'freelancer123',
    role: 'freelancer',
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL'],
    experience: '5 лет коммерческой разработки. Работал в Яндексе и Mail.ru. Специализируюсь на создании высоконагруженных веб-приложений.',
    portfolio: [
      { id: 'p1', title: 'E-commerce платформа', url: 'https://github.com' },
      { id: 'p2', title: 'CRM система', url: 'https://github.com' },
    ],
    rating: 4.8,
    reviewsCount: 24,
    hourlyRate: 3500,
    completedJobs: 24,
    activeApplications: 3,
    phone: '+7 (999) 123-45-67',
    createdAt: '2024-01-10T00:00:00Z',
    isBlocked: false,
  },
  {
    id: 'freelancer2',
    name: 'Анна Козлова',
    email: 'anna@example.ru',
    password: 'pass123',
    role: 'freelancer',
    skills: ['Python', 'Django', 'FastAPI', 'Docker', 'AWS'],
    experience: '4 года разработки backend-систем. Эксперт в области машинного обучения и Data Science.',
    portfolio: [
      { id: 'p3', title: 'ML Pipeline', url: 'https://github.com' },
    ],
    rating: 4.9,
    reviewsCount: 18,
    hourlyRate: 4000,
    completedJobs: 18,
    activeApplications: 2,
    phone: '+7 (999) 234-56-78',
    createdAt: '2024-01-15T00:00:00Z',
    isBlocked: false,
  },
  {
    id: 'freelancer3',
    name: 'Игорь Новиков',
    email: 'igor@example.ru',
    password: 'pass123',
    role: 'freelancer',
    skills: ['Flutter', 'React Native', 'Swift', 'Kotlin'],
    experience: '3 года разработки мобильных приложений для iOS и Android.',
    portfolio: [
      { id: 'p4', title: 'Fitness App', url: 'https://github.com' },
      { id: 'p5', title: 'Food Delivery', url: 'https://github.com' },
    ],
    rating: 4.6,
    reviewsCount: 12,
    hourlyRate: 3000,
    completedJobs: 12,
    activeApplications: 5,
    phone: '+7 (999) 345-67-89',
    createdAt: '2024-02-01T00:00:00Z',
    isBlocked: false,
  },
  {
    id: 'freelancer4',
    name: 'Светлана Морозова',
    email: 'sveta@example.ru',
    password: 'pass123',
    role: 'freelancer',
    skills: ['UI/UX', 'Figma', 'CSS', 'React', 'Tailwind CSS'],
    experience: '6 лет UI/UX дизайна и frontend разработки. Создала более 50 уникальных интерфейсов.',
    portfolio: [
      { id: 'p6', title: 'Design System', url: 'https://figma.com' },
      { id: 'p7', title: 'Landing Pages', url: 'https://github.com' },
    ],
    rating: 5.0,
    reviewsCount: 31,
    hourlyRate: 2500,
    completedJobs: 31,
    activeApplications: 1,
    phone: '+7 (999) 456-78-90',
    createdAt: '2024-01-20T00:00:00Z',
    isBlocked: false,
  },
  {
    id: 'freelancer5',
    name: 'Роман Фёдоров',
    email: 'roman@example.ru',
    password: 'pass123',
    role: 'freelancer',
    skills: ['Go', 'Kubernetes', 'Docker', 'AWS', 'PostgreSQL'],
    experience: '7 лет DevOps и backend разработки. Настройка CI/CD, оркестрация контейнеров.',
    portfolio: [
      { id: 'p8', title: 'Microservices Architecture', url: 'https://github.com' },
    ],
    rating: 4.7,
    reviewsCount: 15,
    hourlyRate: 5000,
    completedJobs: 15,
    activeApplications: 2,
    phone: '+7 (999) 567-89-01',
    createdAt: '2024-02-05T00:00:00Z',
    isBlocked: false,
  },
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job1',
    title: 'Разработка интернет-магазина на React',
    description: 'Нужен опытный React-разработчик для создания полноценного интернет-магазина с корзиной, оплатой и личным кабинетом. Дизайн уже готов в Figma.',
    budget: 150000,
    deadline: '2025-08-01',
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL'],
    clientId: 'client1',
    status: 'open',
    applications: [
      { id: 'app1', jobId: 'job1', freelancerId: 'freelancer1', message: 'Готов взяться за проект! Есть опыт в разработке e-commerce.', status: 'pending', createdAt: '2025-06-15T10:00:00Z' },
    ],
    createdAt: '2025-06-14T09:00:00Z',
  },
  {
    id: 'job2',
    title: 'Backend API на Python/FastAPI',
    description: 'Требуется разработать REST API для мобильного приложения. Нужна авторизация, работа с базой данных, кэширование через Redis.',
    budget: 80000,
    deadline: '2025-07-20',
    skills: ['Python', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker'],
    clientId: 'client2',
    freelancerId: 'freelancer2',
    status: 'in_progress',
    applications: [
      { id: 'app2', jobId: 'job2', freelancerId: 'freelancer2', message: 'Имею богатый опыт в FastAPI и PostgreSQL.', status: 'accepted', createdAt: '2025-06-10T11:00:00Z' },
    ],
    createdAt: '2025-06-08T08:00:00Z',
  },
  {
    id: 'job3',
    title: 'Мобильное приложение на Flutter',
    description: 'Нужно мобильное приложение для доставки еды. iOS и Android. Интеграция с картами, оплатой.',
    budget: 200000,
    deadline: '2025-09-01',
    skills: ['Flutter', 'Dart', 'REST API'],
    clientId: 'client1',
    status: 'open',
    applications: [],
    createdAt: '2025-06-18T14:00:00Z',
  },
  {
    id: 'job4',
    title: 'UI/UX дизайн корпоративного сайта',
    description: 'Нужен дизайн корпоративного сайта. 10 страниц, адаптивность, брендбук предоставлен.',
    budget: 40000,
    deadline: '2025-07-10',
    skills: ['UI/UX', 'Figma'],
    clientId: 'client2',
    freelancerId: 'freelancer4',
    status: 'done',
    applications: [
      { id: 'app3', jobId: 'job4', freelancerId: 'freelancer4', message: 'Специализируюсь именно на корпоративных сайтах!', status: 'accepted', createdAt: '2025-06-05T09:00:00Z' },
    ],
    createdAt: '2025-06-01T10:00:00Z',
  },
  {
    id: 'job5',
    title: 'DevOps — настройка CI/CD и Docker',
    description: 'Настройка пайплайна CI/CD на GitHub Actions, докеризация приложения, деплой на AWS ECS.',
    budget: 60000,
    deadline: '2025-07-15',
    skills: ['Docker', 'Kubernetes', 'AWS', 'Go'],
    clientId: 'client1',
    status: 'open',
    applications: [
      { id: 'app4', jobId: 'job5', freelancerId: 'freelancer5', message: 'Делал подобные задачи десятки раз.', status: 'pending', createdAt: '2025-06-17T16:00:00Z' },
    ],
    createdAt: '2025-06-16T11:00:00Z',
  },
  {
    id: 'job6',
    title: 'Парсер данных на Python',
    description: 'Нужен скрипт для парсинга данных с нескольких сайтов с сохранением в PostgreSQL. Ротация прокси, обход блокировок.',
    budget: 25000,
    deadline: '2025-07-05',
    skills: ['Python', 'PostgreSQL'],
    clientId: 'client2',
    status: 'paid',
    applications: [],
    createdAt: '2025-05-20T09:00:00Z',
  },
];

export const INITIAL_MESSAGES: Message[] = [
  {
    id: 'msg1',
    jobId: 'job2',
    senderId: 'client2',
    text: 'Привет! Когда сможете приступить к работе?',
    createdAt: '2025-06-12T10:00:00Z',
  },
  {
    id: 'msg2',
    jobId: 'job2',
    senderId: 'freelancer2',
    text: 'Здравствуйте! Готова начать прямо сейчас. Уже изучила ТЗ.',
    createdAt: '2025-06-12T10:15:00Z',
  },
  {
    id: 'msg3',
    jobId: 'job2',
    senderId: 'client2',
    text: 'Отлично! Вот дополнительные материалы по проекту.',
    file: '/files/tech_spec.pdf',
    fileName: 'tech_spec.pdf',
    createdAt: '2025-06-12T10:30:00Z',
  },
  {
    id: 'msg4',
    jobId: 'job4',
    senderId: 'freelancer4',
    text: 'Работа готова! Загрузила все макеты в Figma.',
    file: '/files/designs.zip',
    fileName: 'дизайн_корп_сайт.zip',
    createdAt: '2025-06-20T15:00:00Z',
  },
  {
    id: 'msg5',
    jobId: 'job4',
    senderId: 'client2',
    text: 'Замечательно, всё выглядит отлично! Принимаю работу.',
    createdAt: '2025-06-20T15:30:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev1',
    fromUserId: 'client2',
    toUserId: 'freelancer4',
    clientId: 'client2',
    freelancerId: 'freelancer4',
    jobId: 'job4',
    rating: 5,
    text: 'Светлана отличный специалист! Работа выполнена в срок, качество превзошло ожидания.',
    createdAt: '2025-06-20T16:00:00Z',
  },
  {
    id: 'rev2',
    fromUserId: 'client1',
    toUserId: 'freelancer1',
    clientId: 'client1',
    freelancerId: 'freelancer1',
    jobId: 'job1',
    rating: 5,
    text: 'Дмитрий — профессионал высочайшего уровня. Сдал проект раньше срока!',
    createdAt: '2025-06-10T12:00:00Z',
  },
  {
    id: 'rev3',
    fromUserId: 'client2',
    toUserId: 'freelancer2',
    clientId: 'client2',
    freelancerId: 'freelancer2',
    jobId: 'job6',
    rating: 5,
    text: 'Анна быстро справилась с задачей, чётко следовала ТЗ.',
    createdAt: '2025-06-01T09:00:00Z',
  },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'comp1',
    reporterId: 'client1',
    targetId: 'freelancer3',
    reason: 'Не выходит на связь уже 3 дня',
    status: 'pending',
    createdAt: '2025-06-18T11:00:00Z',
  },
];